title: "Sorrento-Lab: a homelab journal"
description: "A journal of building a homelab using OrangeFR 2Gbps fibre, Proxmox, OPNsense, UnRaid and more..."
remote_theme: pmarsceill/just-the-docs
color_scheme: colour1
search_enabled: false

# Define Jekyll collections
collections:
  # Define a collection named "docs", its documents reside in the "_docs" directory
  docs:
    permalink: "/:collections/:path/"
    output: true
  docs2:
    permalink: "/_docs/docs2/"
    output: true
  

just_the_docs:
  # Define which collections are used in just-the-docs
  collections:
    # Reference the "docs" collection
    docs:
      # Give the collection a name
      name: Documentation1
      # Exclude the collection from the navigation
      # Supports true or false (default)
      nav_exclude: false
      # Exclude the collection from the search
      # Supports true or false (default)
      search_exclude: false
    docs2:
      name: Documentation2
      nav_exclude: false
      search_exclude: false
